#---------------------------------#
#    environment configuration    #
#---------------------------------#
language: csharp
os:
  - linux
  - osx
sudo: required
dist: xenial
osx_image: xcode9.2 # OS X 10.12
mono: latest

addons:
  apt:
    - fsharp